# Generated by Django 4.0.4 on 2022-10-05 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_newpost_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='post',
        ),
        migrations.AddField(
            model_name='newpost',
            name='follow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.follow'),
        ),
    ]
