# Generated by Django 4.0.4 on 2022-10-08 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follow_people_follow_alter_follow_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='is_atctive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='people_follow',
            field=models.ManyToManyField(blank=True, default=None, related_name='people_follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
