# Generated by Django 4.0.4 on 2022-10-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_newpost_is_atctive_alter_follow_people_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newpost',
            old_name='is_atctive',
            new_name='is_active',
        ),
    ]
